pub mod adapter;
pub mod config;
pub mod domain;
pub mod events;
pub mod execution;
pub mod health;
pub mod observability;
pub mod planner;
pub mod precision;
pub mod reconcile;
pub mod risk;
pub mod runtime;
pub mod persistence;
pub mod service;
pub mod state;

pub use config::{AppConfig, GridMode};
pub use domain::{GridLevel, OrderIntent, OrderSide, OrderType, PlannerOutput, Position, RiskDecision, RiskReason};
pub use events::{RuntimeEvent, RuntimeEventKind};
pub use execution::{ExecutionEngine, ExecutionPlan, ExistingOrder, ReconciliationDiff, SyncGridResult};
pub use health::{HealthIssue, PauseReason, RuntimeHealth, ServiceState};
pub use planner::GridPlanner;
pub use precision::{normalize_order_qty, normalize_position_size, order_precision_decimals, price_precision_decimals};
pub use reconcile::{FillMetrics, FillSource, ReconcileEngine, ReconcileOutcome, ReconcileSnapshot, SyntheticFill};
pub use risk::RiskEngine;
pub use runtime::ShadowRuntime;
pub use persistence::{JsonFilePersistence, RuntimeCheckpoint};
pub use service::{GridBotService, ServiceCycleOutput};
pub use state::{InMemoryStateStore, RuntimeState};
